---
- name: 'Wordpress Installation On Amazon Linux'
  hosts: aws
  become: yes
  gather_facts: no
  vars:
    domain: www.example.com
    mysql_root: Mysqlroot@123
    mysql_username: wordpress
    mysql_password: Wordpress@123!#
    mysql_database: wordpress

  tasks:
    - name: 'LampStack - Installation'
      yum:
        name:
          - httpd
          - php
          - php-mysql
          - mariadb-server
          - MySQL-python
        state: latest

    - name: 'LampStack - Restarting/Enabling'
      service:
        name: "{{item}}"
        state: restarted
        enabled: yes
      with_items:
        - mariadb
        - httpd

    - name: 'LampStack - Creating Virtualhost'
      template:
        src: virtualhost.j2
        dest: /etc/httpd/conf.d/{{domain}}.conf

    - name: 'LampStack - Creating Documentroot'
      file:
        path: /var/www/html/{{domain}}
        state: directory


    - name: 'LampStack - Creating info.html'
      copy:
        content: "<h1><center>info.html is working</center></h1>"
        dest: /var/www/html/{{domain}}/info.html

    - name: 'LampStack - Creating info.php'
      copy:
        content: "<?php phpinfo(); ?>"
        dest: /var/www/html/{{domain}}/info.php

    - name: 'MariaDb - Resetting Root Password'
      ignore_errors: yes
      mysql_user:
        login_user: root
        login_password: ''
        name: root
        host_all: yes
        password: "{{ mysql_root }}"

    - name: 'MariaDb - Removing Anonymous Users'
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root }}"
        name: ''
        host_all: yes
        state: absent

    - name: 'MariaDb - Creating Wordpress Database'
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root }}"
        db: "{{ mysql_database }}"
        state: present


    - name: 'MariaDb - Creating WordPress User and Privileges'
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root }}"
        name: "{{ mysql_username }}"
        host: localhost
        password: "{{mysql_password}}"
        priv: "{{mysql_database}}.*:ALL"

    - name: 'Wordpress - Downloading'
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: 'Wordpress - Extraction'
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/{{domain}}
        remote_src: yes


    - name: 'Wordpress - Creating wp-config.php'
      template:
        src: wp-config.php.j2
        dest: /var/www/html/{{domain}}/wp-config.php

    - name: 'LampStack - Final Restarting'
      service:
        name: "{{item}}"
        state: restarted
      with_items:
        - mariadb
        - httpd
